int main()
{
  printi(1 + 2);
  printi(1 - 2);
  printi(1 * 2);
  printi(100 / 2);
  printi(99);
  printib(1 == 2);
  printib(1 == 1);
  printi(99);
  printib(1 != 2);
  printib(1 != 1);
  printi(99);
  printib(1 < 2);
  printib(2 < 1);
  printi(99);
  printib(1 <= 2);
  printib(1 <= 1);
  printib(2 <= 1);
  printi(99);
  printib(1 > 2);
  printib(2 > 1);
  printi(99);
  printib(1 >= 2);
  printib(1 >= 1);
  printib(2 >= 1); 
  return 0;
}
